CREATE DATABASE TICKET_MANAGEMENT_V3_DB;

CREATE TABLE USERS (
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	EMAIL_ID VARCHAR(50) UNIQUE NOT NULL,
	PASSWORD VARCHAR(10) NOT NULL,
	ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
	);
SELECT * FROM USERS;

CREATE TABLE ROLES (
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(10) NOT NULL UNIQUE,
	ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
	);
SELECT * FROM ROLES;

CREATE TABLE DEPARTMENTS (
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
	);
SELECT * FROM DEPARTMENTS;

CREATE TABLE EMPLOYEES (
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	DEPARTMENT_ID INT UNSIGNED NOT NULL,
	ROLE_ID INT UNSIGNED NOT NULL,
	EMAIL_ID VARCHAR(50) UNIQUE NOT NULL,
	PASSWORD VARCHAR(10) NOT NULL,
	ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT FK_DEPARTMENT_ID FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID),
	CONSTRAINT FK_ROLE_ID FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ID)
	);
SELECT * FROM EMPLOYEES;

CREATE TABLE PRIORITIES (
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(10) NOT NULL UNIQUE,
	ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
	);
SELECT * FROM PRIORITIES;

CREATE TABLE TICKETS (
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	USER_ID INT UNSIGNED NOT NULL,
	SUBJECT VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	DEPARTMENT_ID INT UNSIGNED NOT NULL,
	PRIORITY_ID INT UNSIGNED NOT NULL,
	CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ASSIGNED_EMPLOYEE_ID INT UNSIGNED,
	RESOLVED_DATETIME TIMESTAMP,
	STATUS VARCHAR(10) NOT NULL DEFAULT 'Open',
	ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT FK_USER_ID_TICKET FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
	CONSTRAINT FK_DEPARTMENT_ID_TICKET FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID),
	CONSTRAINT FK_PRIORITY_ID_TICKET FOREIGN KEY(PRIORITY_ID) REFERENCES PRIORITIES(ID),
	CONSTRAINT FK_EMPLOYEE_ID_TICKET FOREIGN KEY(ASSIGNED_EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
	);
SELECT * FROM TICKETS;

CREATE TABLE ISSUES (
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	TICKET_ID INT UNSIGNED NOT NULL,
	SOLUTION TEXT NOT NULL,
	CONSTRAINT FK_TICKET_ID FOREIGN KEY(TICKET_ID) REFERENCES TICKETS(ID)
	);
SELECT * FROM ISSUES;